unstable_features = true

hard_tabs = true
newline_style = "Unix"

max_width = 100
fn_call_width = 80
attr_fn_like_width = 100
chain_width = 100
doc_comment_code_block_width = 100

format_code_in_doc_comments = true
format_macro_matchers = true

imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
match_arm_blocks = false
match_block_trailing_comma = true
overflow_delimited_expr = true
reorder_impl_items = true
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
condense_wildcard_suffixes = true
